version: "3.8"
services:
  express-api:
    build: 
      context: ./API
    volumes: 
        - ./API/:/API
    ports:
        - 5000:5000
    image: express-api:API
    container_name: express-api
    command: npm start
