version: "3.8"
services:
  backend-app:
    build: ./backend-app
    image: backend_app
    ports: 
      - 8080:8080
    volumes:
      - ./backend-app/src:/backend-app/src
  ocpp-server:
    build: ./ocpp
    image: ocpp
    ports:
      - 1337:1337
    volumes:
      - ./ocpp/src:/ocpp/src