openapi: 3.0.0
info:
  title: FlexiCharge API
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: Development Environment
paths:
  /auth/sign-in:
    post:
      summary: User sign in.
      responses:
        '200':
          description: testing